import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const envPath = path.join(projectRoot, '.env');

function toEnvValue(value) {
  if (typeof value === 'string') {
    return JSON.stringify(value);
  }

  return JSON.stringify(String(value));
}

function randomHex(bytes = 16) {
  return randomBytes(bytes).toString('hex');
}

function loadExistingEnv() {
  if (!fs.existsSync(envPath)) {
    return {};
  }

  const entries = {};
  const content = fs.readFileSync(envPath, 'utf8');

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const separatorIndex = line.indexOf('=');
    if (separatorIndex === -1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    let value = line.slice(separatorIndex + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    entries[key] = value;
  }

  return entries;
}

function createEnvContent(existing = {}) {
  const passcode = existing.ATTENDANCE_ADMIN_PASSCODE || `attendance-${randomHex(8)}`;
  const sessionSecret = existing.ADMIN_SESSION_SECRET || randomHex(32);
  const firebaseApiKey = existing.VITE_FIREBASE_API_KEY || existing.FIREBASE_API_KEY || 'Al92JI';
  const firebaseAuthDomain = existing.VITE_FIREBASE_AUTH_DOMAIN || existing.FIREBASE_AUTH_DOMAIN || 'geo-location-.firebaseapp.com';
  const firebaseProjectId = existing.VITE_FIREBASE_PROJECT_ID || existing.FIREBASE_PROJECT_ID || 'geo-location-';
  const firebaseStorageBucket = existing.VITE_FIREBASE_STORAGE_BUCKET || existing.FIREBASE_STORAGE_BUCKET || 'geo-location-.firebasestorage.app';
  const firebaseMessagingSenderId = existing.VITE_FIREBASE_MESSAGING_SENDER_ID || existing.FIREBASE_MESSAGING_SENDER_ID || '191628';
  const firebaseAppId = existing.VITE_FIREBASE_APP_ID || existing.FIREBASE_APP_ID || '1:1c47bffd346d';

  const values = {
    ATTENDANCE_ADMIN_PASSCODE: passcode,
    ADMIN_SESSION_SECRET: sessionSecret,
    FIREBASE_API_KEY: firebaseApiKey,
    FIREBASE_AUTH_DOMAIN: firebaseAuthDomain,
    FIREBASE_PROJECT_ID: firebaseProjectId,
    FIREBASE_STORAGE_BUCKET: firebaseStorageBucket,
    FIREBASE_MESSAGING_SENDER_ID: firebaseMessagingSenderId,
    FIREBASE_APP_ID: firebaseAppId,
    VITE_FIREBASE_API_KEY: firebaseApiKey,
    VITE_FIREBASE_AUTH_DOMAIN: firebaseAuthDomain,
    VITE_FIREBASE_PROJECT_ID: firebaseProjectId,
    VITE_FIREBASE_STORAGE_BUCKET: firebaseStorageBucket,
    VITE_FIREBASE_MESSAGING_SENDER_ID: firebaseMessagingSenderId,
    VITE_FIREBASE_APP_ID: firebaseAppId,
    VITE_ATTENDANCE_API_BASE: existing.VITE_ATTENDANCE_API_BASE || '',
  };

  const lines = [
    '# Generated by scripts/generate-env.mjs',
    '# Firebase Web SDK config is public browser configuration.',
    '',
  ];

  for (const [key, value] of Object.entries(values)) {
    lines.push(`${key}=${toEnvValue(value)}`);
  }

  return `${lines.join('\n')}\n`;
}

const existingEnv = loadExistingEnv();
const envContent = createEnvContent(existingEnv);
fs.writeFileSync(envPath, envContent, 'utf8');
console.log(`Created ${path.relative(projectRoot, envPath)}`);
